# Generated by Django 5.0.6 on 2024-06-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_face_encoding'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('encoding', models.BinaryField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
